/* Generated By:JavaCC: Do not edit this line. CCalParserTreeConstants.java Version 5.0 */
public interface CCalParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVAR = 2;
  public int JJTCONST = 3;
  public int JJTFUNCTION = 4;
  public int JJTTYPE = 5;
  public int JJTNEMPARL = 6;
  public int JJTMAIN = 7;
  public int JJTSTATEMENT = 8;
  public int JJTASSIGN = 9;
  public int JJTFUNCASSIGN = 10;
  public int JJTPLUS_OP = 11;
  public int JJTMINUS_OP = 12;
  public int JJTFUNCRETURN = 13;
  public int JJTMINUS = 14;
  public int JJTBOOLOP = 15;
  public int JJTCONDITION = 16;
  public int JJTANDOP = 17;
  public int JJTOROP = 18;
  public int JJTCOMP = 19;
  public int JJTEQUALS = 20;
  public int JJTNOTEQUALS = 21;
  public int JJTLESSTHAN = 22;
  public int JJTLESSEQUAL = 23;
  public int JJTGREATERTHAN = 24;
  public int JJTGREATEREQUAL = 25;
  public int JJTARGLIST = 26;
  public int JJTID = 27;


  public String[] jjtNodeName = {
    "program",
    "void",
    "Var",
    "Const",
    "Function",
    "Type",
    "NemParL",
    "Main",
    "Statement",
    "Assign",
    "FuncAssign",
    "Plus_op",
    "Minus_op",
    "FuncReturn",
    "Minus",
    "BoolOp",
    "Condition",
    "AndOp",
    "OrOp",
    "Comp",
    "Equals",
    "NotEquals",
    "LessThan",
    "LessEqual",
    "GreaterThan",
    "GreaterEqual",
    "ArgList",
    "ID",
  };
}
/* JavaCC - OriginalChecksum=0721388a19fbf54571fe6c76b1802749 (do not edit this line) */
