/* Generated By:JJTree: Do not edit this line. GreaterEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class GreaterEqual extends SimpleNode {
  public GreaterEqual(int id) {
    super(id);
  }

  public GreaterEqual(CCalParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CCalParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ebc2cfc9ccc1171d98f9b7f5586cbcf3 (do not edit this line) */
